nelmio_api_doc:
    documentation:
        info:
            title: Notification App API
            description: Api Docs
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
